name: Deploy to CloudHub

on:
  push:
    branches:
      - main  # or the branch you want to trigger on

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK-11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Deploy to Exchange
      run: mvn clean deploy -DskipTests -DbusinessGroupId=29e2f09f-0b24-4f6a-8092-aa17da7ee9ef


    - name: Deploy to CloudHub
      run: mvn mule:deploy -Danypoint.username=${{ secrets.ANYPOINT_USERNAME }} -Danypoint.password=${{ secrets.ANYPOINT_PASSWORD }} -e -X
