name: Deploy to CloudHub 2.0

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Maven settings.xml for Anypoint Exchange
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings>
            <servers>
              <server>
                <id>Repository</id>
                <username>${{ secrets.ANYPOINT_USERNAME }}</username>
                <password>${{ secrets.ANYPOINT_PASSWORD }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Package Application
        run: mvn clean package -DskipTests

      - name: Deploy to Exchange
        run: mvn deploy -DskipTests -DbusinessGroupId=29e2f09f-0b24-4f6a-8092-aa17da7ee9ef

      - name: Deploy to CloudHub 2.0
        run:  mvn mule:deploy -Danypoint.username=${{ secrets.ANYPOINT_USERNAME }} -Danypoint.password=${{ secrets.ANYPOINT_PASSWORD }} -DskipDeploymentVerification=true
